############################### meta_library ############################### > start
article:
  body:
    meta_library:
      author:
        avatar: https://image.luxu.site/avatar-violet.webp # 虽然没有 ssl 证书, 仍然写 https, 否则 hexo 无法加载成功
        name: Luxury
        url: /
############################### meta_library ############################### > end

############################### Cover ############################### > start

cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: false
    others: false
  search: Search...
  features:

############################### Cover ############################### > end

############################### Navigation Bar ############################### > start

# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  visiable: always # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: Luxury
  menu:
    - name:
      search: Search...   # Search bar placeholder

custom_css:
  navbar:
    width: max # auto, max

############################### Navigation Bar ############################### > end

############################### Sidebar ############################### > start

sidebar:
  position: right # left right 侧边栏的位置
  for_page: [category] # 主页、分类、归档等独立页面的组件
  for_post: [toc] # docs/post 这类文章页面
  
############################### Sidebar ############################### > end

############################### Site Footer ############################### > start

site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer]

############################### Site Footer ############################### > end

############################### Comments ############################### > start
comments: false
############################### Comments ############################### > end

############################### Plugins ############################### > start

plugins:
  # APlayer is only available in mainland China.
  aplayer:
    enable: true
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 411796573    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#D23A32'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.5       # default volume, notice that player will remember user setting
    list_max_height: 320px # list max height
    list_folded: true
    autoHide: true    # hide automaticaly
  darkmodejs:
    enable: true
  # 背景图片滚动播放
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)

############################### Plugins ############################### > end
